# Generated by Django 3.0.7 on 2020-06-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_useraccount_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='signup_date',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='password',
            field=models.TextField(default='', verbose_name='Test'),
        ),
    ]
