# Generated by Django 3.0.7 on 2020-06-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200625_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='interest',
            field=models.DecimalField(choices=[(0.02, '2%'), (0.05, '5%'), (0.1, '10%')], decimal_places=2, default=0.02, max_digits=4),
        ),
    ]
