# Generated by Django 3.0.7 on 2020-06-25 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200625_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='interest',
        ),
    ]
